name: frontend deploy

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Repository
        uses: actions/checkout@v4

      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Upgrade npm
        run: npm install -g npm@10.8.1

      - name: Check npm version
        run: npm -v

      - name: Setup environment variables
        run: |
          cp .env .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: CI='false' npm run build

      - name: Upload frontend build file to artifact
        uses: actions/upload-artifact@v4
        with:
          name: FrontendApplication
          path: build

  deploy:
    needs: build-and-upload
    runs-on: [ self-hosted, prod ]
    steps:

      - name: Remove previous version app
        run: rm -rf build

      - name: Download build file from artifact
        uses: actions/download-artifact@v4
        with:
          name: FrontendApplication
          path: build

      - name: debug current dir
        run: pwd

      - name: Deploy Frontend
        run: /home/ubuntu/actions-runner/_work/front/front/run.sh